### PR TITLE
Did some stylings on new booking

### PR DESCRIPTION
**Pull request by mohednazari**

### CODE REVIEW

**Comment by ozdere** [comment]
Hi @mohednazari can you share a screenshot for the intended result? Date picker currently shows the whole month and looks broken to me. Shouldn't it display the month only **after** clicking on the date field?

screenshot-2022-09-10-at-15-42-32

**Comment by mohednazari** [comment]
image

This is how it looks for me.
About the date picker I change the code to below: 
```
data: {
  controller: "flatpickr",
  **inline: true,**
  flatpickr_date_format: "Y-m-d",
  flatpickr_min_date: Time.current,
  flatpickr_max_date: Time.current + 90.days,
  flatpickr_disable: @booked_dates
  },
  **placeholder: "Select a date", style: "display: none;"%>**
```

inline:true => will show the calendar
placeholder: "Select a date", style: "display: none;"%> => will hide the select date field

I have made this changes for  better styling

**Comment by sarhan-a** [comment]
Thanks @mohednazari , In my case I could still see a bit of the footer which was not looking good, I have changed that and brought the submit button a bit down and made a few tweaks. The labels for city, address etc were not centered so fixed that.
The calendar has a new theme now, I chose green just to bring some more of it from the logo, but we can change that easy to other colours.

 I think @ozdere was refering to the prompt for selecting a date so I have added a description above the calendar to help the user.

@ozdere I think it would be good to have the date initially selected on the hompage persisted on this calendar and maybe a few of the other search queries.

It still looks a bit too big and plenty of space on the right side so this file may have to be reviewed again if time allows for it.

image

**Review by sarhan-a — APPROVED** [review]
Made a few changes. See my previous comment. Thanks

**Comment by mohednazari** [comment]
@sarhan-a Thanks for applying the changes. Makes look even better. I agree on the right, there is some space left maybe we can add an image on the right side or above the form and calendar to give some more visuals on this page. That automatically moves the footer to the bottom as well. Please note that because you changed the button position, the button is not working. Let me know if you want me to fix it or if you'll do it your self.

**Comment by sarhan-a** [comment]
@mohednazari there seems to be something funny about this form, I even reverted to your version and still it is buggy,
You need to refresh first before being able to book, 
I am looking into it but would appreciate your help with this.

**Pull request merged**
